# Generated by Django 4.1.7 on 2023-03-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tfidf_matrix', models.BinaryField()),
                ('cosine_sim', models.BinaryField()),
            ],
        ),
    ]
