# Generated by Django 4.1.7 on 2023-05-06 00:36

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_former_price_product_total_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='images'),
        ),
    ]
